title: "Koottali"
email: marketing@koottali.com
timezone: UTC
url: https://koottali.com
baseurl: "/"
permalink: "/:title/"
logo: "assets/images/logo.png"
favicon: "assets/images/ktnew.svg"
author: koottali
paginate: 30
disqus: "koottali.com"
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: G-016V8HJ3KD

# Authors
authors:
  sal:
    name: Sal
    display_name: Sal
    avatar: "assets/images/sal.png"
    email: marketing@koottali.com
    web: https://www.koottali.com
    twitter: https://twitter.com/koottali
    description: "Author of Affiliates, a template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  john:
    name: Koottali
    display_name: Koottali
    avatar: "assets/images/john.png"
    email: marketing@koottali.com
    web: https://www.koottali.com/
    twitter: https://twitter.com/koottali
    description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."

# Social
social:
  instagram: https://www.instagram.com/koottaliapp/
  facebook: https://www.facebook.com/profile.php?id=100063668094904
  twitter: https://twitter.com/koottali

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
